"""create utils branch

Revision ID: e54a6a77d721
Revises:
Create Date: 2025-01-07 15:31:52.201188

"""
from typing import Sequence, Union

from alembic import op
from alembic_utils.pg_function import PGFunction

# revision identifiers, used by Alembic.
revision: str = 'e54a6a77d721'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('utils',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_hermes_dummy = PGFunction(
        schema="public",
        signature="hermes_dummy()",
        definition='''RETURNS void AS $$\n  BEGIN
                -- No operation\n  END;\n  $$ LANGUAGE plpgsql'''
    )
    op.replace_entity(public_hermes_dummy)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_hermes_dummy = PGFunction(
        schema="public",
        signature="hermes_dummy()",
        definition='''RETURNS void AS $$\n  BEGIN
                -- No operation\n  END;\n  $$ LANGUAGE plpgsql'''
    )
    op.drop_entity(public_hermes_dummy)

    # ### end Alembic commands ###
