"""add indexes for modelruns

Revision ID: cd951716a1c8
Revises: ce906ec117f1
Create Date: 2025-12-05 13:01:57.900508

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd951716a1c8'
down_revision: Union[str, None] = 'ce906ec117f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index('idx_modelresult_gridcell_oid',
                    'modelresult', ['gridcell_oid'],
                    unique=False, if_not_exists=True)
    op.create_index('idx_modelresult_modelrun_gridcell',
                    'modelresult', ['modelrun_oid', 'gridcell_oid'],
                    unique=False, if_not_exists=True)
    op.create_index('idx_modelresult_modelrun_timestep',
                    'modelresult', ['modelrun_oid', 'timestep_oid'],
                    unique=False, if_not_exists=True)
    op.create_index('idx_modelresult_timestep_oid',
                    'modelresult', ['timestep_oid'],
                    unique=False, if_not_exists=True)
    op.create_index('idx_timestep_oid',
                    'timestep', ['oid'],
                    unique=False, if_not_exists=True)
    op.create_index('idx_gridcell_oid',
                    'gridcell', ['oid'],
                    unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_modelresult_timestep_oid', table_name='modelresult')
    op.drop_index('idx_modelresult_modelrun_timestep',
                  table_name='modelresult')
    op.drop_index('idx_modelresult_modelrun_gridcell',
                  table_name='modelresult')
    op.drop_index('idx_modelresult_gridcell_oid', table_name='modelresult')
    op.drop_index('idx_timestep_oid', table_name='timestep')
    op.drop_index('idx_gridcell_oid', table_name='gridcell')
    # ### end Alembic commands ###
